steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - client-demo/google-cloud-aapl/Dockerfile
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/${PROJECT_ID}/deltasignal/aapl-client-demo:latest
options:
  logging: CLOUD_LOGGING_ONLY
